language: java

jdk:
  - oraclejdk8

install: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true

script: mvn test

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master